server:
  port: 8080

spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: ${BREVO_SMTP_LOGIN}
    password: ${BREVO_SMTP_KEY}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: ${JWT_SECRET}
  expirationMs: ${JWT_EXPIRATION_MS}

site:
  owner:
    email: ${SITE_OWNER_EMAIL}

admin:
  email: ${ADMIN_EMAIL}

mongo:
  api:
    public:
      key: ${MONGO_API_PUBLIC_KEY}
    private:
      key: ${MONGO_API_PRIVATE_KEY}
  project:
    id: ${MONGO_PROJECT_ID}

logging:
  level:
    org:
      springframework:
        web:
          client: DEBUG
      apache:
        http: DEBUG